### ISSUE TITLE
Nil pointer dereference when using protoset option

### ISSUE THREAD

**Issue by kchristidis** [fullstorydev/grpcurl#9]
(Thanks for this project!)

Assume a simple service like the one described in [extended.proto](https://github.com/kchristidis/nested/blob/master/lib/extended/extended.proto), and libprotoc 3.5.1 installed.

I generate `extended.protoset`:

```bash
$ protoc --proto_path=$GOPATH/src --descriptor_set_out=extended.protoset --include_imports $GOPATH/src/github.com/kchristidis/nested/lib/extended/extended.proto
```
Then, when invoking `grpcurl`, I get:

```bash
$ grpcurl -protoset extended.protoset list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x114de11]

goroutine 1 [running]:
github.com/golang/protobuf/protoc-gen-go/descriptor.(*FileDescriptorProto).GetName(...)
	/Users/kchrist/Go/src/github.com/jhump/protoreflect/desc/descriptor.go:77
github.com/jhump/protoreflect/desc.CreateFileDescriptor(0xc4201982d0, 0xc42004b400, 0x2, 0x2, 0x2, 0xc42004b400, 0x1)
	/Users/kchrist/Go/src/github.com/jhump/protoreflect/desc/descriptor.go:77 +0x1d1
github.com/fullstorydev/grpcurl.resolveFileDescriptor(0xc42017e2a0, 0xc42017e2d0, 0xc420018740, 0x39, 0xc420169380, 0x0, 0x0)
	/Users/kchrist/Go/src/github.com/fullstorydev/grpcurl/grpcurl.go:110 +0x2c2
github.com/fullstorydev/grpcurl.DescriptorSourceFromFileDescriptorSet(0xc42015ba38, 0xc42004b3a0, 0x2, 0x2, 0xc42004b290)
	/Users/kchrist/Go/src/github.com/fullstorydev/grpcurl/grpcurl.go:86 +0x1d1
github.com/fullstorydev/grpcurl.DescriptorSourceFromProtoSets(0xc42004b170, 0x1, 0x1, 0xc4200165d0, 0xc420059d80, 0x15219e4, 0x6)
	/Users/kchrist/Go/src/github.com/fullstorydev/grpcurl/grpcurl.go:75 +0x505
main.main()
	/Users/kchrist/Go/src/github.com/fullstorydev/grpcurl/cmd/grpcurl/grpcurl.go:230 +0x34c
```

What am I doing wrong?

**Comment by jhump** [comment]
Oh, yikes. This is a serious bug. I think my testing of the protoset stuff was insufficient. I'll send a patch.

**Comment by jhump** [comment]
I just noticed that the example proto and protoset file that the tests use doesn't actually have any imports, which is why existing tests failed to catch this. My early exploratory tests must have been similar, and failed to actually exercise these lines of code.

**Comment by kchristidis** [comment]
Hm, I'm still seeing this, even with the latest master.

**Comment by jhump** [comment]
@kchristidis, I can't reproduce. I just checked out latest master of the grpcurl source and ran the following:

```bash
go get github.com/kchristidis/nested
protoc --proto_path=$GOPATH/src --descriptor_set_out=extended.protoset \
    --include_imports $GOPATH/src/github.com/kchristidis/nested/lib/extended/extended.proto
go install github.com/fullstorydev/grpcurl/cmd/grpcurl
grpcurl -protoset extended.protoset list
``` 

And I get no errors:

```
> grpcurl -protoset extended.protoset list
common.Get
extended.Get
```

**Comment by kchristidis** [comment]
Ah, I know what I did wrong. I was careless and running `go install` on the repo's root directory.

Works like a charm now. Thanks for the quick turnaround!
